Stemmer = require('../lib/stemmer').Stemmer

describe 'stemmer', ->

  it 'should lowercase words', ->
    expect(Stemmer.stem("ABC")).toBe("abc")

  it 'should remove apostrophes', ->
    expect(Stemmer.removeApostrophe("a'bc")).toBe("a'bc")
    expect(Stemmer.removeApostrophe("bryan's")).toBe("bryan")
    expect(Stemmer.removeApostrophe("jesus'")).toBe("jesus")

  it 'should pass the sample vocabulary', ->
    cases = [
      ["consign", "consign"]
      ["consigned", "consign"]
      ["consigning", "consign"]
      ["consignment", "consign"]
      ["consist", "consist"]
      ["consisted", "consist"]
      ["consistency", "consist"]
      ["consistent", "consist"]
      ["consistently", "consist"]
      ["consisting", "consist"]
      ["consists", "consist"]
      ["consolation", "consol"]
      ["consolations", "consol"]
      ["consolatory", "consolatori"]
      ["console", "consol"]
      ["consoled", "consol"]
      ["consoles", "consol"]
      ["consolidate", "consolid"]
      ["consolidated", "consolid"]
      ["consolidating", "consolid"]
      ["consoling", "consol"]
      ["consolingly", "consol"]
      ["consols", "consol"]
      ["consonant", "conson"]
      ["consort", "consort"]
      ["consorted", "consort"]
      ["consorting", "consort"]
      ["conspicuous", "conspicu"]
      ["conspicuously", "conspicu"]
      ["conspiracy", "conspiraci"]
      ["conspirator", "conspir"]
      ["conspirators", "conspir"]
      ["conspire", "conspir"]
      ["conspired", "conspir"]
      ["conspiring", "conspir"]
      ["constable", "constabl"]
      ["constables", "constabl"]
      ["constance", "constanc"]
      ["constancy", "constanc"]
      ["constant", "constant"]
      ["knack", "knack"]
      ["knackeries", "knackeri"]
      ["knacks", "knack"]
      ["knag", "knag"]
      ["knave", "knave"]
      ["knaves", "knave"]
      ["knavish", "knavish"]
      ["kneaded", "knead"]
      ["kneading", "knead"]
      ["knee", "knee"]
      ["kneel", "kneel"]
      ["kneeled", "kneel"]
      ["kneeling", "kneel"]
      ["kneels", "kneel"]
      ["knees", "knee"]
      ["knell", "knell"]
      ["knelt", "knelt"]
      ["knew", "knew"]
      ["knick", "knick"]
      ["knif", "knif"]
      ["knife", "knife"]
      ["knight", "knight"]
      ["knightly", "knight"]
      ["knights", "knight"]
      ["knit", "knit"]
      ["knits", "knit"]
      ["knitted", "knit"]
      ["knitting", "knit"]
      ["knives", "knive"]
      ["knob", "knob"]
      ["knobs", "knob"]
      ["knock", "knock"]
      ["knocked", "knock"]
      ["knocker", "knocker"]
      ["knockers", "knocker"]
      ["knocking", "knock"]
      ["knocks", "knock"]
      ["knopp", "knopp"]
      ["knot", "knot"]
      ["knots", "knot"]
    ]
    #for testCase in cases
      #expect(Stemmer.stem(testCase[0])).toBe(testCase[1])
